### ISSUE TITLE
ライセンスの調整

### ISSUE THREAD

**Issue by neguse11** [neguse11/CM3D2.GearMenu#1]
ライセンス定義に関するお願い

@CM3D2-01
GearMenuのライセンス定義を行うために、基のgist「[CM3D2：SystemShortcutにボタン追加](https://gist.github.com/CM3D2-01/adcf5072ff5ba812858a)」のライセンスを定義してもらえないでしょうか？

(現状のまま「『ライセンスは未定義』と定義する」という形式でもかまいません)
### 経緯

改造スレその４で以下のようなやりとりがありました

その４>>804

> ＞＞799
> GearMenu関連のソースについてはどう取り扱えばいいの？
> ライセンス不明瞭だと他人が登録しようとすると破綻するorライセンス的にブラックな気がするけど 

その４>>827 (neguse11)

> ＞＞804
> GearMenuはCM3D2-01さんのコード >>671 が起源なので、改変後のものについても起源コードのライセンスに従います。
> ということでよろしくお願いします！＞CM3D2-01さん
> 他のコードのライセンスは考えたことが無かったので、適当に探して WTFPL Version 2 にしました 

その結果[cm3d2_plugins_okiba](https://github.com/neguse11/cm3d2_plugins_okiba/blob/master/ABOUT-LICENSE.md)には[WTFPL](http://www.wtfpl.net/about/)を指定しています。
ただし、GearMenuについては基にしたコードがそのまま残っているので、ライセンスは未定義のままにしています。
### 個人的な見解
- コードを再利用する側からすると、何らかのライセンスが明示されていたほうが利便性が高いのは確かです。
- が、個人的には未定義のままでも大きな問題は無いと楽観しています。
  - この場合は @neguse11 の改変部分について何らかのライセンスを定義し、基のコードについては未定義とする、という形式にします
- また、このライセンスの定義によって @neguse11 が @CM3D2-01 さんに何らかの責任を一方的に押し付けるつもりはありません。
  - 具体的には、（開発者でなければ）もう１段起源を遡るとデコンパイルしたコードですから、デコンパイルした結果を一般に公表したリスクがあります
  - この点について問題が起きた場合に @neguse11 は「これはアイツが勝手に公開したものだし、ボクちゃん知らないも～ん」等の言い逃れをしません

**Comment by CM3D2-01** [comment]
READMEに注意書き追加しました。

現状こういうModはKISSが緩く放任する感じ？だけど、そうは言っても非公式Modなので、
個人的には、基本的に全てグレーゾーンなんだと言う認識での下で改造勢の「暗黙の了解」に任せたい。
ソース自体は煮るなり焼くなり好きにして良い完全自由方針だけど
Modの位置付け上おおっぴらに「再配布おｋ！」とか言うもんでもないよね的な。

**Comment by neguse11** [comment]
ありがとう！　[ライセンスの項](https://github.com/neguse11/CM3D2.GearMenu#%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9)を追加しました。

> 基本的に全てグレーゾーンなんだと言う認識

この一点に尽きると思っています。

以下ちょっと調べた結果
- GitHub でライセンスを指定しないとどうなるの？　→　指定しなくてもいいけど、指定したほうが良いよ！
  - [What happens if I don't choose a license?](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license)
- CM3D と CM3D2 のアップデータのページを見比べると、CM3D2では「●リバースエンジニアリングによる解析結果の公表等を禁止します。」の文言が削除されている
  - http://www.kisskiss.tv/cm3d/update.php
  - http://www.kisskiss.tv/cm3d2/update.php
  - 推奨するわけでもないのだろうけど……
